name: Release Obsidian plugin

on:
    push:
        tags:
            - "*"
env:
    PLUGIN_NAME: obsidian-diary-merger

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
              with:
                  # 禁用自动源码压缩包的关键设置
                  fetch-depth: 0

            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "18.x"

            - name: Build and Package
              id: package
              run: |
                  npm install
                  npm run build

                  # 创建包含所有文件的ZIP
                  ZIP_FILE="${{ env.PLUGIN_NAME }}-${GITHUB_REF#refs/tags/}.zip"
                  zip -r "$ZIP_FILE" main.js manifest.json styles.css

                  # 保存ZIP文件名供后续步骤使用
                  echo "ZIP_FILE=$ZIP_FILE" >> $GITHUB_ENV
                  echo "::set-output name=zip_file::$ZIP_FILE"

            - name: Create Release
              uses: softprops/action-gh-release@v1
              with:
                  tag_name: ${{ github.ref_name }}
                  name: Release ${{ github.ref_name }}
                  files: ${{ env.ZIP_FILE }}
                  generate_release_notes: true
                  draft: false
                  prerelease: false
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
